# Generated by Django 4.0.6 on 2022-10-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomWebApp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('8.5', '8.5')], default='7', max_length=10),
        ),
    ]
