# Generated by Django 4.0.6 on 2022-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomWebApp', '0006_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='outfit',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Classic', 'Classic')], default='casual', max_length=10),
        ),
    ]
