# Generated by Django 4.0.6 on 2022-10-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomWebApp', '0008_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank='True', null=True),
        ),
    ]
