# Generated by Django 4.0.6 on 2022-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomWebApp', '0010_customer_order_product_digital_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
