# Generated by Django 4.0.6 on 2022-10-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomWebApp', '0011_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank='True', default=0, null=True),
        ),
    ]
